version: '3.7'
services:
  janus-gateway:
    image: hobakc/docker-janus-gateway:latest
    container_name: janus-gateway
    build: .
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "7088:7088"
      - "8088:8088"
      - "8188:8188"
      - "10000-10200:10000-10200/udp"
    environment:
      - DOCKER_IP=${DOCKER_IP}
    restart: unless-stopped
